Add recommended search keywords
PPAV-inc/telegram-bot pull request #131
Opened 2018-01-11 16:17 UTC by xxhomey19

<img width="412" alt="screen shot 2018-01-12 at 12 15 48 am" src="https://user-images.githubusercontent.com/12113222/34834795-ec2ff5d0-f72d-11e7-86bc-741b2e4483af.png">

2018-01-11 16:36 UTC, LittleWhiteYA commented on src/bot/locale/traditionalChinese.js
> +      '一月份 PPAV x 奧視 特別企劃 ⁉️\n請輸入：*奧視*\n即可進入 PPAV 免費專區 ⁉️\n\n操作說明：\n\n1️⃣*隨機熱門影片* 請輸入： "*PPAV*" 或點擊下方主選單中的 "PPAV 熱門"\n\n2️⃣*隨機最新影片* 請輸入： "*PPAV new*" 或點擊下方主選單中的 "PPAV 最新"\n\n3️⃣*搜尋影片* 請輸入： "*# 關鍵字*"\
這要不要把時間直接拿掉？

2018-01-11 16:47 UTC, xxhomey19 commented on src/bot/locale/traditionalChinese.js
> +      '一月份 PPAV x 奧視 特別企劃 ⁉️\n請輸入：*奧視*\n即可進入 PPAV 免費專區 ⁉️\n\n操作說明：\n\n1️⃣*隨機熱門影片* 請輸入： "*PPAV*" 或點擊下方主選單中的 "PPAV 熱門"\n\n2️⃣*隨機最新影片* 請輸入： "*PPAV new*" 或點擊下方主選單中的 "PPAV 最新"\n\n3️⃣*搜尋影片* 請輸入： "*# 關鍵字*"\
@aresyuan

2018-01-12 11:08 UTC, aresyuan commented on src/bot/locale/traditionalChinese.js
> +      '一月份 PPAV x 奧視 特別企劃 ⁉️\n請輸入：*奧視*\n即可進入 PPAV 免費專區 ⁉️\n\n操作說明：\n\n1️⃣*隨機熱門影片* 請輸入： "*PPAV*" 或點擊下方主選單中的 "PPAV 熱門"\n\n2️⃣*隨機最新影片* 請輸入： "*PPAV new*" 或點擊下方主選單中的 "PPAV 最新"\n\n3️⃣*搜尋影片* 請輸入： "*# 關鍵字*"\
也行，目前看起來應該是會穩定合作

2018-01-17 14:18 UTC, LittleWhiteYA requested changes
等時間拿掉

2018-01-17 14:18 UTC, LittleWhiteYA commented on src/bot/locale/traditionalChinese.js
> +      '一月份 PPAV x 奧視 特別企劃 ⁉️\n請輸入：*奧視*\n即可進入 PPAV 免費專區 ⁉️\n\n操作說明：\n\n1️⃣*隨機熱門影片* 請輸入： "*PPAV*" 或點擊下方主選單中的 "PPAV 熱門"\n\n2️⃣*隨機最新影片* 請輸入： "*PPAV new*" 或點擊下方主選單中的 "PPAV 最新"\n\n3️⃣*搜尋影片* 請輸入： "*# 關鍵字*"\
@xxhomey19

2018-01-20 10:33 UTC, LittleWhiteYA approved these changes

2018-01-20 10:36 UTC, merged